#index:
#    path: /
#    controller: App\Controller\DefaultController::index

facture_index:
    path: /factures
    controller: App\Controller\FactureController::index

app_add_facture:
    path: /facture/create
    controller: App\Controller\FactureController::create
    methods: [GET]


